SELECT COUNT(*) AS num_unsatisfactory_grades
FROM ExamResults e
WHERE e.grade < 4 AND e.exam_date BETWEEN TO_DATE('01-JAN-' || EXTRACT(YEAR FROM CURRENT_TIMESTAMP), 'DD-MON-YYYY') AND TO_DATE('31-JAN-' || EXTRACT(YEAR FROM CURRENT_TIMESTAMP), 'DD-MON-YYYY');